alias 'g'='git status'
alias 'gpul'='git pull origin $(current_branch)'
alias 'gpus'='git push origin $(current_branch)'
alias 'gre'='git reset'
alias 'greh'='git reset --hard'
alias 'glog'='git log'
alias 'gadd'='git add'
