alias 'df'='df -h -x tmpfs'
alias 'ls'='ls --color=auto -h'
alias 'du'='du -h'
alias 'grep'='grep --color=auto -n'
alias 'less'='less -M -R'
alias 'free'='free -m'
alias 'nano'='nano -icW'

alias -g M=' | more'
alias -g L=' | less'
alias -g H=' | head'
alias -g T=' | tail'
alias -g G=' | grep'
alias -g N='2>/dev/null'
